### ISSUE TITLE
including form-display-if functionality?

### ISSUE THREAD

**Issue by rouilj** [aarongustafson/form-required-if#2]
I don't know how you feel about this, but it seems this would also work well to remove a
class from the enclosed label/field when something is selected.

E.G.
```
<style>
  .conditional_display {
  display: none;
</style>
<form-required-if conditions="email=*" indicator="<b>*</b>" remove_class="conditional_display">
  <label  class="conditional_display>Required if there’s an email value
    <input type="text" name="depends-on-email-or-test">
  </label>
</form-required-if>
```

The class could go on the `form-required-if-conditions` tag.

Doing this as a class rather than adding/removing a `hidden` attribute allows the developer to transition
to auto once that is available in all browsers. (It might be possible to do the same with `[hidden]` in css but
....)

**Comment by aarongustafson** [comment]
I haven't tested, but what about something like this? 

```css
form-required-if label.conditional_display {
  display: none;
}

form-required-if label.conditional_display:has([required]) {
  display: block;
}
```
